name: Build and Test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Upgrade pip and install requests
      run: python -m pip install --upgrade build requests
    - name: Download the NAIF DE440 file
      run: python naif_de440/fetch.py
    - name: Install naif_de440
      run: pip install .[tests]
    - name: Test naif_de440
      run: pytest .
